### ISSUE TITLE
Early Suggestions

### ISSUE THREAD

**Issue by SHOTbyGUN** [mabako/reddit-for-city-skylines#1]
1. There is no readme file on root, add it and add from there to your configuration wiki page please, also to other important pages.
2. There is no Linux configuration path displayed on configuration wiki page, I found it here 
   ~/.local/share/Colossal Order/Cities_Skylines/ModConfig/reddit-for-chirpy.txt
3. Also please add link to the chirp filter mod on readme page as recommened mod.

**Comment by mabako** [comment]
I've done 1 and 2, not too sure about the third thing mentioned.

I've started working on a little bit of work in regards of replacing the default messages at https://github.com/mabako/reddit-for-city-skylines/commit/e00ab5a51327ba674477a9276097f464af6fd4dd and this, by extend, means it'll be incompatible to the chirp filter if I publish it?

**Comment by SHOTbyGUN** [comment]
Thanks :+1: closing
